spring.application.name=PRODUCTSERVICE
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/ProductDb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#spring.datasource.url=jdbc:h2:mem:productDB
#spring.h2.console.enabled=true





