spring.application.name=gateway
server.port=8980

# Eureka Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.service-registry.auto-registration.enabled=true


# Discovery locator
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# ROUTES with updated keys

# Route to Product Service
spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCTSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/product-service/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

# Route to Order Service
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ORDERSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/order-service/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1




