spring.application.name=ORDERSERVICE
server.port=8082

# PostgreSQL DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/OrderDb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.service-registry.auto-registration.enabled=true

#circuite breaker
resilience4j.circuitbreaker.instances.PRODUCTSERVICE.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.PRODUCTSERVICE.sliding-window-size=5
resilience4j.circuitbreaker.instances.PRODUCTSERVICE.wait-duration-in-open-state=10000

management.endpoints.web.exposure.include=*
management.health.circuitbreakers.enabled=true
resilience4j.circuitbreaker.register-health-indicator=true

# Allow retryable (connection) errors to trigger circuit breaker
resilience4j.circuitbreaker.ignore-exceptions=org.springframework.web.client.HttpClientErrorException
resilience4j.circuitbreaker.record-exceptions=feign.RetryableException,java.net.ConnectException,java.io.IOException




